= How do you feel about your job?

Responses of the participants are as follows

== Participant 1
I like my job because I am able to help many people by staying at one place.

== Participant 2
I like my job because the AIM of my profession is very good, but due to work setting and work load sometimes it gets tough.

== Participant 3
i like my job but there is little pressure.

== Participant 4
Nursing job is very good, there is no problem for it, I feel very good in myself that I am able to serve someone.

== Participant 5
I am starting to like my nursing job now but earlier I was not much interested.

== Participant 6
I really like my job very much, I am working since 2 years and It is my endeavor everyday that I stay focused in my working hours and can give proper patient care.

== Participant 7
I think my job is fine but there is some problem regarding work setting.

== Participant 8
I think my job is good, that means it seems fine.

== Participant 9
i like my job.

== Participant 10
Job is fine for me. Earlier I thought it is easy but after coming here I came to know that it is not that easy either.

== Participant 11
To be honest, I really like my job.

== Participant 12
If I want to explain, I feel a lot about my job. Sometimes it seems stressful, but at the end of the day, I get a very good satisfaction that I have been able to help someone so much.

== Participant 13
i like my job. 

== Participant 14
I like my job my profession very much. There has never been any regressive feeling for sucking in this profession or working here in this profession.

== Participant 15
i like my job.

== Participant 16
I like my job, sometimes there is a problem but overall it looks good.

== Participant 17
Job is fine.

== Participant 18
Yes job is good, profession is also good.

== Participant 19
job is good.

== Participant 20
i like this job and this profession.